feature: teste

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,22 +1,28 @@
 name: Print Information
 
-on: [push, pull_request]
+on:
+  workflow_dispatch:
 
 jobs:
-  print:
+  job1:
     runs-on: ubuntu-latest
-    if: "!startsWith(github.event.head_commit.message, 'Merge') || github.event.pull_request.draft == false"
+    outputs:
+      output1: ${{ steps.test_output.outputs.test }}\
     steps:
-      - name: Checkout Github
-        uses: actions/checkout@v3
-
-      - name: Extract branch name
-        id: extract_branch
-        run: echo "::set-output name=BRANCH_REF::$(echo ${GITHUB_REF#refs/})"
-
-      - name: Update Changelog
-        run: echo "${{ steps.extract_branch.outputs.BRANCH_REF }}"
-
-      - name: Dump GitHub context
-        id: github_context_step
-        run: echo '${{ toJSON(github) }}'
+      - name: Test outputs
+        id: test_output
+        run: |
+          cat -d
+          if [ $? == 1 ]
+          then
+            echo "test=failure" >> "$GITHUB_OUTPUT"
+          else
+            echo "test=success" >> "$GITHUB_OUTPUT"
+          fi
+  job2:
+    runs-on: ubuntu-latest
+    needs: job1
+    steps:
+      - env:
+          OUTPUT1: ${{needs.job1.outputs.output1}}
+        run: echo "$OUTPUT1"
